# /********************************************************************************
# * Copyright (c) 2022,2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: kuksa_dbc_feeder

on:
  pull_request:
    paths:
      - ".github/workflows/kuksa_dbc_feeder.yml"
      - "dbc2val/**"
  workflow_call:
  workflow_dispatch:

jobs:
  build-can-feeder-image:
    name: "Build multi-arch image"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/eclipse/kuksa.val.feeders/dbc2val
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      if: needs.checkrights.outputs.have_secrets == 'true'
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build DBC provider container container and push to ghcr.io (and ttl.sh)
      id: ghcr-build
      if: ${{ needs.checkrights.outputs.have_secrets == 'true' && github.event_name != 'pull_request' }}
      uses: docker/build-push-action@v3
      with:
        platforms: |
          linux/amd64
          linux/arm64
        file: ./dbc2val/Dockerfile
        context: ./dbc2val/
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
          ttl.sh/kuksa.val/kuksa-dbcprovider-${{github.sha}}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build ephemeral DBC provider container and push to ttl.sh
      if: ${{ needs.checkrights.outputs.have_secrets == 'false' || github.event_name == 'pull_request' }}
      id: tmp-build
      uses: docker/build-push-action@v3
      with:
        platforms: |
          linux/amd64
          linux/arm64
        file: ./dbc2val/Dockerfile
        context: ./dbc2val/
        push: true
        tags: "ttl.sh/kuksa.val/kuksa-dbcprovider-${{github.sha}}"
        labels: ${{ steps.meta.outputs.labels }}

    - name: Posting message
      uses: ./.github/actions/post-container-location
      with:
        image: ttl.sh/kuksa.val/kuksa-dbcprovider-${{github.sha}}

    - name: Run dbc tests
      run: |
        cd dbc2val
        pip3 install --no-cache-dir -r requirements.txt -r requirements-dev.txt
        python -m pytest

    - name: Run pylint (but accept errors for now)
      run: |
        cd dbc2val
        # First just show, never fail
        pylint --exit-zero dbcfeeder.py dbcfeederlib test
        # Fail on errors and above
        pylint -E dbcfeeder.py dbcfeederlib test
