# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: kuksa_dbc_feeder_release

on:
  # workflow_dispatch:   #TODO: input versions manually
  push:
    tags:
      - "v*.*.*"

jobs:
  # reusable workflow issues: https://github.community/t/ref-head-in-reusable-workflows/203690/27

  kuksa_dbc_feeder:
    name: Build
    uses: ./.github/workflows/kuksa_dbc_feeder.yml
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      [
        kuksa_dbc_feeder,
      ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: bin/
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
  release-feeder-can-image:
    name: "Download and push to ghcr (feeder_can)"
    runs-on: ubuntu-latest

    needs: [kuksa_dbc_feeder]
    steps:
      - id: repository-name-adjusted
        name: Prepare repository name in lower case for docker upload. This supports repository names in mixed case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Retrieve saved Docker image
        uses: actions/download-artifact@v3
        with:
          name: Container image
          path: ${{github.workspace}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Push image to ghcr"
        env:
          VAL_NAME: dbc2val
          VAL_VERSION: ${{ steps.get_version.outputs.version }}
          GIT_HUB_REPOSITORY_NAME_LOWER_CASE: ${{ steps.repository-name-adjusted.outputs.lowercase }}
        shell: bash
        run: |
          skopeo copy --all oci-archive:dbc2val.tar "docker://ghcr.io/$GIT_HUB_REPOSITORY_NAME_LOWER_CASE/$VAL_NAME:$VAL_VERSION"
          skopeo inspect --raw "docker://ghcr.io/$GIT_HUB_REPOSITORY_NAME_LOWER_CASE/$VAL_NAME:$VAL_VERSION" | jq
          skopeo inspect "docker://ghcr.io/$GIT_HUB_REPOSITORY_NAME_LOWER_CASE/$VAL_NAME:$VAL_VERSION"
