# /********************************************************************************
# * Copyright (c) 2022,2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: kuksa_csv_provider

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - ".github/workflows/kuksa_csv_provider.yml"
      - ".github/actions/post-container-location/action.yml"
      - "csv_provider/**"
  workflow_dispatch:

concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true

jobs:
  check_ghcr_push:
    uses: eclipse-kuksa/kuksa-actions/.github/workflows/check_ghcr_push.yml@2
    secrets: inherit

  run-csv-provider-tests:
    name: "Run csv provider linter"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run pylint (but accept errors for now)
      run: |
        cd csv_provider
        pip3 install --no-cache-dir -r requirements.txt
        pip3 install --no-cache-dir pylint
        # First just show, never fail
        pylint --exit-zero provider.py
        # Fail on errors and above
        pylint -E provider.py

  build-csv-provider-image:
    name: "Build csv provider image"
    runs-on: ubuntu-latest
    needs: check_ghcr_push

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/eclipse/kuksa.val.feeders/csv-provider
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      if: needs.check_ghcr_push.outputs.push == 'true'
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build CSV provider container and push to ghcr.io (and ttl.sh)
      id: ghcr-build
      if: needs.check_ghcr_push.outputs.push == 'true'
      uses: docker/build-push-action@v3
      with:
        platforms: |
          linux/amd64
          linux/arm64
        file: ./csv_provider/Dockerfile
        context: ./csv_provider/
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
          ttl.sh/kuksa.val/kuksa-csvprovider-${{github.sha}}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build ephemeral CSV provider container and push to ttl.sh
      if: needs.check_ghcr_push.outputs.push == 'false'
      id: tmp-build
      uses: docker/build-push-action@v3
      with:
        platforms: |
          linux/amd64
          linux/arm64
        file: ./csv_provider/Dockerfile
        context: ./csv_provider/
        push: true
        tags: "ttl.sh/kuksa.val/kuksa-csvprovider-${{github.sha}}"
        labels: ${{ steps.meta.outputs.labels }}

    - name: Posting message
      uses: ./.github/actions/post-container-location
      with:
        image: ttl.sh/kuksa.val/kuksa-csvprovider-${{github.sha}}
