# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: kuksa_dds_feeder

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - ".github/workflows/kuksa_dds_feeder.yml"
      - "dds2val/**"
  workflow_dispatch:

concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true

jobs:
  check-dds-feeder:
    name: "Check DDS feeder"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Retrieve build binaries
      uses: actions/download-artifact@v3
      with:
        path: ${{github.workspace}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - id: repository-name-adjusted
      name: Make repository name in lower case for docker upload.
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ github.repository }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: build linux/amd64 docker image
      id: image_build_amd64
      uses: docker/build-push-action@v4
      with:
        pull: true
        push: false
        outputs: |
          type=oci,dest=./dds2val_amd64.tar
        context: ./dds2val
        file: ./dds2val/Dockerfile
        build-args: |
          TARGETPLATFORM=linux/amd64
        tags: ${{ github.sha }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{steps.repository-name-adjusted.outputs.lowercase}}

    - name: Temporarily save linux/amd64 Docker image
      uses: actions/upload-artifact@v3
      with:
        name: Container image
        path: ${{github.workspace}}/dds2val_amd64.tar
        retention-days: 1

    - name: build linux/arm64 docker image
      id: image_build_arm64
      uses: docker/build-push-action@v4
      with:
        pull: true
        push: false
        outputs: |
          type=oci,dest=./dds2val_arm64.tar
        context: ./dds2val
        file: ./dds2val/Dockerfile
        build-args: |
          TARGETPLATFORM=linux/arm64
          TARGETARCH=arm64
        tags: ${{ github.sha }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{steps.repository-name-adjusted.outputs.lowercase}}

    - name: Temporarily save linux/arm64 Docker image
      uses: actions/upload-artifact@v3
      with:
        name: Container image
        path: ${{github.workspace}}/dds2val_arm64.tar
        retention-days: 1

    - name: Run dds tests
      run: |
        cd dds2val
        # Note - if relying on kuksa-client pre-releases you must use --pre on the line below
        pip3 install --no-cache-dir -r requirements/requirements.txt -r requirements/requirements-kml.txt -r requirements/requirements-test.txt
        ./ddsproviderlib/idls/generate_py_dataclass.sh
        python -m pytest tests/*
