# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: kuksa_dbc_feeder

on:
  pull_request:
    paths:
      - ".github/workflows/kuksa_dbc_feeder.yml"
      - "dbc2val/**"
  workflow_call:
  workflow_dispatch:

jobs:
  build-can-feeder-image:
    name: "Build multi-arch image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Retrieve build binaries
        uses: actions/download-artifact@v3
        with:
          path: ${{github.workspace}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: repository-name-adjusted
        name: Make repository name in lower case for docker upload.
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: "Build image"
        id: image_build
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: false
          outputs: |
            type=oci,dest=./dbc2val.tar
          context: ./dbc2val
          file: ./dbc2val/Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: ${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{steps.repository-name-adjusted.outputs.lowercase}}

      - name: Temporarily save Docker image
        uses: actions/upload-artifact@v3
        with:
          name: Container image
          path: ${{github.workspace}}/dbc2val.tar
          retention-days: 1

      - name: Run dbc tests
        run: |
          cd dbc2val
          pip3 install --no-cache-dir -r requirements-dev.txt
          python -m pytest

      - name: Run pylint (but accept errors for now)
        run: |
          cd dbc2val
          # First just show, never fail
          pylint --exit-zero dbcfeeder.py dbcfeederlib test
          # Fail on errors and above
          pylint -E dbcfeeder.py dbcfeederlib test
